/* Generated by restful-react */

import React from "react";
import { Get, GetProps, useGet, UseGetProps } from "restful-react";

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export interface LibraryRssPodcast {
  url?: string | null;
  id?: number;
}

export type GetLibraryRssPodcastsProps = Omit<GetProps<LibraryRssPodcast[], unknown, void>, "path">;

/**
 * Get all library RSS podcasts.
 */
export const GetLibraryRssPodcasts = (props: GetLibraryRssPodcastsProps) => (
  <Get<LibraryRssPodcast[], unknown, void>
    path={`/Api/LibraryRssPodcast`}
    {...props}
  />
);

export type UseGetLibraryRssPodcastsProps = Omit<UseGetProps<LibraryRssPodcast[], void>, "path">;

/**
 * Get all library RSS podcasts.
 */
export const useGetLibraryRssPodcasts = (props: UseGetLibraryRssPodcastsProps) => useGet<LibraryRssPodcast[], unknown, void>(`/Api/LibraryRssPodcast`, props);


export type GetLibraryRssPodcastByIdProps = Omit<GetProps<LibraryRssPodcast, unknown, void>, "path"> & {id: number};

/**
 * Get a library RSS podcast by ID.
 */
export const GetLibraryRssPodcastById = ({id, ...props}: GetLibraryRssPodcastByIdProps) => (
  <Get<LibraryRssPodcast, unknown, void>
    path={`/Api/LibraryRssPodcast/${id}`}
    {...props}
  />
);

export type UseGetLibraryRssPodcastByIdProps = Omit<UseGetProps<LibraryRssPodcast, void>, "path"> & {id: number};

/**
 * Get a library RSS podcast by ID.
 */
export const useGetLibraryRssPodcastById = ({id, ...props}: UseGetLibraryRssPodcastByIdProps) => useGet<LibraryRssPodcast, unknown, void>(`/Api/LibraryRssPodcast/${id}`, props);


export interface GetOidcConfigurationClientRequestParametersResponse {
  [key: string]: string;
}

export type GetOidcConfigurationClientRequestParametersProps = Omit<GetProps<GetOidcConfigurationClientRequestParametersResponse, unknown, void>, "path"> & {clientId: string};

export const GetOidcConfigurationClientRequestParameters = ({clientId, ...props}: GetOidcConfigurationClientRequestParametersProps) => (
  <Get<GetOidcConfigurationClientRequestParametersResponse, unknown, void>
    path={`/_configuration/${clientId}`}
    {...props}
  />
);

export type UseGetOidcConfigurationClientRequestParametersProps = Omit<UseGetProps<GetOidcConfigurationClientRequestParametersResponse, void>, "path"> & {clientId: string};

export const useGetOidcConfigurationClientRequestParameters = ({clientId, ...props}: UseGetOidcConfigurationClientRequestParametersProps) => useGet<GetOidcConfigurationClientRequestParametersResponse, unknown, void>(`/_configuration/${clientId}`, props);

