/* Generated by restful-react */

import React from "react";
import { Get, GetProps, useGet, UseGetProps } from "restful-react";

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export interface LibraryRssPodcast {
  url?: string | null;
  id?: number;
}

export interface WeatherForecast {
  date?: string;
  temperatureC?: number;
  temperatureF?: number;
  summary?: string | null;
}

export type GetLibraryRssPodcastsProps = Omit<GetProps<LibraryRssPodcast[], unknown, void>, "path">;

/**
 * Get all library RSS podcasts.
 */
export const GetLibraryRssPodcasts = (props: GetLibraryRssPodcastsProps) => (
  <Get<LibraryRssPodcast[], unknown, void>
    path={`/api/Podcasts/LibraryRssPodcasts`}
    {...props}
  />
);

export type UseGetLibraryRssPodcastsProps = Omit<UseGetProps<LibraryRssPodcast[], void>, "path">;

/**
 * Get all library RSS podcasts.
 */
export const useGetLibraryRssPodcasts = (props: UseGetLibraryRssPodcastsProps) => useGet<LibraryRssPodcast[], unknown, void>(`/api/Podcasts/LibraryRssPodcasts`, props);


export interface GetLibraryRssPodcastQueryParams {
  id?: number;
}

export type GetLibraryRssPodcastProps = Omit<GetProps<LibraryRssPodcast, unknown, GetLibraryRssPodcastQueryParams>, "path">;

/**
 * Get a library RSS podcast by ID.
 */
export const GetLibraryRssPodcast = (props: GetLibraryRssPodcastProps) => (
  <Get<LibraryRssPodcast, unknown, GetLibraryRssPodcastQueryParams>
    path={`/api/Podcasts/LibraryRssPodcast`}
    {...props}
  />
);

export type UseGetLibraryRssPodcastProps = Omit<UseGetProps<LibraryRssPodcast, GetLibraryRssPodcastQueryParams>, "path">;

/**
 * Get a library RSS podcast by ID.
 */
export const useGetLibraryRssPodcast = (props: UseGetLibraryRssPodcastProps) => useGet<LibraryRssPodcast, unknown, GetLibraryRssPodcastQueryParams>(`/api/Podcasts/LibraryRssPodcast`, props);


export type GetWeatherForecastsProps = Omit<GetProps<WeatherForecast[], unknown, void>, "path">;

export const GetWeatherForecasts = (props: GetWeatherForecastsProps) => (
  <Get<WeatherForecast[], unknown, void>
    path={`/api/WeatherForecast`}
    {...props}
  />
);

export type UseGetWeatherForecastsProps = Omit<UseGetProps<WeatherForecast[], void>, "path">;

export const useGetWeatherForecasts = (props: UseGetWeatherForecastsProps) => useGet<WeatherForecast[], unknown, void>(`/api/WeatherForecast`, props);

